(()=>{
const key='medicinal-pages-demo-v1', userKey=key+'-user', nativeFetch=window.fetch.bind(window);
const clone=x=>JSON.parse(JSON.stringify(x));
const fail=message=>{throw Error(message)};
const safeUrl=(s,media=false)=>typeof s==='string'&&(!s||s.startsWith('/')&&!s.startsWith('//')||s.startsWith('#')||/^https:\/\//.test(s)||/^(assets\/|index\.html)/.test(s)||(media&&/^data:image\/(png|jpeg|webp);base64,/.test(s)));
function urlCheck(s,media=false){if(!safeUrl(s,media))fail('Use an HTTPS URL or a local /path.');return s;}
function amount(v,nullable=false){if(nullable&&(v===null||v===''))return null;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>10000000||Math.abs(Math.round(v*100)-v*100)>0.000001)fail('Enter a valid nonnegative amount with up to two decimals.');return v;}
function textValue(v,max=500){if(typeof v!=='string'||v.length>max)fail('Invalid or overly long text.');return v.trim();}
function variantPrice(p,v){return v.price??p.salePrice??p.regularPrice;}
function canBuy(p,v,s){if(p.status!=='published'||['Out of Stock','Coming Soon','Unavailable','Hidden'].includes(p.availability))return false;return p.preorder?s.preordersEnabled:v.stock>0;}
function publicProduct(p,s){const price=p.salePrice??p.regularPrice;return {...p,price,desc:p.description,image:p.images[0]?.url||'',colors:[...new Set(p.variants.map(v=>v.color))],sizes:[...new Set(p.variants.map(v=>v.size))],type:p.preorder?'PRE-ORDER':'ORDER',badge:p.bestSeller?'BESTSELLER':p.newArrival?'NEW':'',purchasable:p.variants.some(v=>canBuy(p,v,s)),variants:p.variants.map(v=>({...v,effectivePrice:variantPrice(p,v),purchasable:canBuy(p,v,s)}))};}
function validateProduct(b,old){const p={id:old?.id||crypto.randomUUID(),name:textValue(b.name,160),description:textValue(b.description,5000),category:textValue(b.category,80),collection:textValue(b.collection,100),sku:textValue(b.sku,100),regularPrice:amount(b.regularPrice),salePrice:amount(b.salePrice,true),compareAtPrice:amount(b.compareAtPrice,true),lowStockThreshold:b.lowStockThreshold,releaseDate:b.releaseDate||'',status:b.status,availability:b.availability,featured:!!b.featured,newArrival:!!b.newArrival,bestSeller:!!b.bestSeller,preorder:!!b.preorder,seoTitle:textValue(b.seoTitle,160),seoDescription:textValue(b.seoDescription,500),tags:b.tags,images:b.images};if(!p.name||!p.sku)fail('Name and SKU are required.');if(!['draft','published','archived'].includes(p.status)||!['In Stock','Low Stock','Out of Stock','Pre-order','Coming Soon','Unavailable','Hidden'].includes(p.availability))fail('Invalid product status.');if(p.availability==='Pre-order')p.preorder=true;if(p.releaseDate&&!Number.isFinite(Date.parse(p.releaseDate)))fail('Invalid pre-order date.');if(!Number.isInteger(p.lowStockThreshold)||p.lowStockThreshold<0)fail('Invalid low-stock threshold.');if(p.salePrice!==null&&p.salePrice>p.regularPrice)fail('Sale price cannot exceed regular price.');if(!Array.isArray(p.tags)||p.tags.length>30||p.tags.some(x=>typeof x!=='string'||x.length>80))fail('Invalid tags.');if(!Array.isArray(p.images)||p.images.length>12)fail('Use up to 12 product images.');p.images=p.images.map(x=>({url:urlCheck(x.url,true),publicId:textValue(x.publicId||'',300)}));if(!Array.isArray(b.variants)||!b.variants.length||b.variants.length>100)fail('Add between 1 and 100 variants.');const keys=new Set();p.variants=b.variants.map(v=>{const color=textValue(v.color,80),size=textValue(v.size,40),key=color+' / '+size;if(!color||!size||keys.has(key))fail('Every variant needs a unique color / size combination.');keys.add(key);const prev=old?.variants.find(x=>x.id===v.id);return {id:prev?.id||crypto.randomUUID(),color,size,price:amount(v.price,true),stock:prev?.stock||0};});if(old?.variants.some(v=>!p.variants.some(x=>x.id===v.id)))fail('Existing variants must be retained for order history. Set stock to zero to stop selling them.');return p;}
function validateSettings(b){const s=clone(b);for(const key of ['storeName','contactEmail','contactPhone','address','featuredCollection','shopTitle','aboutHeading','about','footer'])s[key]=textValue(s[key],key==='about'?5000:500);if(!s.storeName)fail('Store name is required.');if(!/^[A-Z]{3}$/.test(s.currency))fail('Use a three-letter currency code.');try{new Intl.NumberFormat('en',{style:'currency',currency:s.currency})}catch{fail('Invalid currency.')}amount(s.shippingFee);amount(s.freeShippingThreshold);for(const key of ['logo','favicon'])urlCheck(s[key],true);for(const val of Object.values(s.social))urlCheck(val);if(!Array.isArray(s.payments)||s.payments.some(x=>!['Cash on Delivery','GCash','Bank Transfer'].includes(x)))fail('Invalid payment methods.');s.preordersEnabled=!!s.preordersEnabled;for(const x of [s.announcement,...s.banners]){for(const k of ['start','end'])if(x[k]&&!Number.isFinite(Date.parse(x[k])))fail('Invalid schedule date.');if(x.start&&x.end&&Date.parse(x.end)<=Date.parse(x.start))fail('End date must be after start date.');}if(s.banners.length>20||s.sections.length>10)fail('Too many homepage sections.');textValue(s.announcement.text,500);urlCheck(s.announcement.link);for(const x of [s.hero,...s.banners]){urlCheck(x.image,true);if(x.mobileImage)urlCheck(x.mobileImage,true);urlCheck(x.url);for(const k of ['heading','description','cta'])textValue(x[k]||'',1000);}for(const x of s.sections){if(!['featured','newArrival','bestSeller','collection'].includes(x.type))fail('Invalid homepage section.');textValue(x.title,100);}return s;}const link=s=>typeof s==='string'&&s.startsWith('/')&&!s.startsWith('//')?(s==='/shop'?'index.html#shop':s==='/'?'index.html':s.slice(1)):s;
function paths(x){if(Array.isArray(x))return x.map(paths);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,paths(v)]));return link(x)}
function read(){return JSON.parse(localStorage.getItem(key)||'null')||{data:paths(clone(window.DEMO_SEED)),revision:0,orders:[],reviews:{},logs:[]}}
function save(s){s.revision++;try{localStorage.setItem(key,JSON.stringify(s))}catch{fail('Browser storage is full. Try a smaller image or use an HTTPS image URL.')}if(window.BroadcastChannel){const c=new BroadcastChannel('store-updates');c.postMessage('updated');c.close()}}
const user=()=>JSON.parse(localStorage.getItem(userKey)||'null');
const now=()=>new Date().toISOString();
const log=(s,p,v,delta,reason)=>s.logs.unshift({id:crypto.randomUUID(),created_at:now(),actor:'Demo user',product_id:p.id,variant:v.color+' / '+v.size,delta,stock:v.stock,reason});
function api(path,b,method){const s=read(),u=user(),settings=s.data.settings;const pth=path.split('?')[0];
 if(pth==='/api/me')return {authenticated:!!u,user:u};
 if(pth==='/api/store')return {revision:s.revision,settings,products:s.data.products.filter(p=>p.status==='published'&&p.availability!=='Hidden').map(p=>publicProduct(p,settings))};
 if(pth==='/api/admin/store')return {...s,database:'Browser demo',localMedia:true};
 if(pth==='/api/admin/media'){if(!/^data:image\/(jpeg|png|webp);base64,/.test(b.data)||b.data.length>1500000)fail('Demo uploads support images under about 1 MB.');return {url:b.data,publicId:''}}
 if(pth==='/api/admin/settings'){s.data.settings=paths(validateSettings(b.settings));save(s);return {ok:true}}
 if(pth==='/api/admin/products'){
  let p=s.data.products.find(p=>p.id===b.id);
  if(b.action==='save'){const next=validateProduct(b.product,p);if(s.data.products.some(x=>x.id!==next.id&&x.sku===next.sku))fail('SKU must be unique.');if(p)s.data.products[s.data.products.indexOf(p)]=paths(next);else s.data.products.push(paths(next))}
  else{if(!p)fail('Product not found.');if(b.action==='duplicate'){p=clone(p);p.id=crypto.randomUUID();p.name+=' (copy)';p.sku+='-COPY-'+p.id.slice(0,4);p.status='draft';p.variants.forEach(v=>{v.id=crypto.randomUUID();v.stock=0});s.data.products.push(p)}else{const statuses={publish:'published',unpublish:'draft',archive:'archived',restore:'draft'};if(!statuses[b.action])fail('Unknown action.');p.status=statuses[b.action]}}
  save(s);return {ok:true};
 }
 if(pth==='/api/admin/inventory'){
  if(method==='GET')return {logs:s.logs,next:null};
  const p=s.data.products.find(p=>p.id===b.productId),v=p?.variants.find(v=>v.id===b.variantId);if(!v)fail('Select a variant.');if(!Number.isInteger(b.quantity)||b.quantity<0||!b.reason.trim())fail('Enter a whole quantity and adjustment reason.');const before=v.stock;const stock=b.action==='set'?b.quantity:b.action==='add'?before+b.quantity:before-b.quantity;if(stock<0)fail('Stock cannot be negative.');v.stock=stock;log(s,p,v,stock-before,b.reason);save(s);return {ok:true};
 }
 if(pth==='/api/admin/orders')return {orders:s.orders};
 if(pth.startsWith('/api/admin/orders/')){const o=s.orders.find(o=>o.id===pth.split('/').pop());if(!o)fail('Order not found.');if(o.status==='Cancelled'&&b.status!=='Cancelled')fail('Create a new demo order instead of reopening a cancelled order.');if(['Shipped','Delivered'].includes(o.status)&&b.status==='Cancelled')fail('Only unfulfilled orders can be cancelled.');if(b.status==='Cancelled'&&o.status!=='Cancelled'){for(const i of o.items){if(i.preorder)continue;const p=s.data.products.find(p=>p.id===i.id),v=p?.variants.find(v=>v.id===i.variantId);if(v){v.stock+=i.qty;log(s,p,v,i.qty,'Demo order cancelled: '+o.id)}}}Object.assign(o,{status:b.status,payment_status:b.payment_status,tracking:b.tracking,notes:b.notes,updated_at:now(),revision:o.revision+1});save(s);return {ok:true}}
 if(pth==='/api/account')return {profile:u,orders:s.orders.filter(o=>o.userId===u?.id)};
 const reviewMatch=pth.match(/^\/api\/products\/([^/]+)\/reviews$/);
 if(reviewMatch){const id=decodeURIComponent(reviewMatch[1]);let reviews=s.reviews[id]||[];if(method==='POST'){if(!u)fail('Sign in to the demo first.');if(!Number.isInteger(b.rating)||b.rating<1||b.rating>5||!b.body?.trim())fail('Choose a rating and write a review.');reviews=reviews.filter(r=>r.userId!==u.id);reviews.push({...b,userId:u.id,customer_name:u.name,updated_at:now()});s.reviews[id]=reviews;save(s)}return {reviews,summary:{count:reviews.length,average:reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:0}}}
 if(pth==='/api/orders'){
  if(!u)fail('Sign in to the demo first.');const existing=s.orders.find(o=>o.requestKey===b.requestKey);if(existing)return {id:existing.id};
  if(!b.items?.length)fail('Your bag is empty.');if(!settings.payments.includes(b.payment))fail('This payment option is unavailable.');for(const k of ['name','email','phone','address','city','postal'])if(!b.customer[k]?.trim())fail('Complete all delivery fields.');
  const items=[];for(const i of b.items){const p=s.data.products.find(p=>p.id===i.id),v=p?.variants.find(v=>v.color===i.color&&v.size===i.size);if(!v||!canBuy(p,v,settings)||!Number.isInteger(i.qty)||i.qty<1||(!p.preorder&&i.qty>v.stock))fail('Item unavailable or insufficient stock.');const price=variantPrice(p,v);if(price!==i.price)fail('Price changed. Please review your bag.');items.push({...i,variantId:v.id,name:p.name,price,preorder:p.preorder,currency:settings.currency});if(!p.preorder){v.stock-=i.qty;log(s,p,v,-i.qty,'Demo checkout')}}
  const subtotal=items.reduce((n,i)=>n+i.price*i.qty,0),shipping=subtotal<settings.freeShippingThreshold?settings.shippingFee:0;
  const o={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),requestKey:b.requestKey,userId:u.id,customer:b.customer,items,total:Math.round((subtotal+shipping)*100)/100,shipping,status:'Pending',payment_status:'Unpaid',payment_method:b.payment,preorder:items.some(i=>i.preorder),created_at:now(),updated_at:now(),revision:0,tracking:'',notes:''};s.orders.unshift(o);save(s);return {id:o.id};
 }
 fail('This demo action is not available.');
}
window.fetch=async(input,options={})=>{const raw=typeof input==='string'?input:input.url;const url=new URL(raw,location.href);if(!url.pathname.startsWith('/api/'))return nativeFetch(input,options);try{return new Response(JSON.stringify(api(url.pathname+url.search,options.body?JSON.parse(options.body):{},options.method||'GET')),{status:200,headers:{'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:400,headers:{'Content-Type':'application/json'}})}};
window.demoSignIn=()=>{localStorage.setItem(userKey,JSON.stringify({id:'demo-customer',name:'Demo Customer',email:'customer@example.com'}))};
window.demoSignOut=()=>localStorage.removeItem(userKey);
document.addEventListener('DOMContentLoaded',()=>{
 const bar=document.createElement('div');bar.style.cssText='background:#d7ff35;color:#09090a;padding:8px 14px;font:12px Inter,Arial,sans-serif;display:flex;justify-content:center;gap:12px;flex-wrap:wrap';bar.innerHTML='<strong>DEMO — No real orders. Changes stay in this browser.</strong><a href="index.html">Store</a><a href="admin.html">Demo admin</a><button id="resetDemo" type="button">Reset demo</button>';document.body.prepend(bar);document.querySelector('#resetDemo').onclick=()=>{if(confirm('Reset demo products, orders, reviews and bag in this browser?')){localStorage.removeItem(key);localStorage.removeItem(userKey);localStorage.removeItem('medicinal-pages-cart');location.href='index.html'}};
 if(location.pathname.endsWith('/account.html')&&!user())location.replace('login.html?return_to=account.html');
 document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const h=a.getAttribute('href');if(h.startsWith('/')&&!h.startsWith('//')){e.preventDefault();location.href=link(h)}});
});
})();
